### ISSUE TITLE
Rescaling issues with non-native W:H ratio

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#112]
If you run toee on a non-native W:H ratio, it'll pad the image with black margins to fit your native W:H.

e.g. if I try to run on 1024:768, fullscreen, when my native resolution is 1600x900, then I'll have black margins at the sides.
This also makes edge scrolling very inconvenient, since then you have to move the cursor to the exact boundary between the black margin and the image.

**Comment by shartte** [comment]
Erm how is the first part a bug? 

If you choose a render resolution with a different aspect ratio it HAS to pad it with black bars. How else would that work?

The scrolling is an issue though. How *should* that work? Should the entire black bar area be considered a scroll-active zone? I can't make the window border the scroll zone, because that is outside of the area considered by the ToEE engine (it only considers the actual rendered area).

**Comment by DudeMcDude** [comment]
I guess you could say the first part is not strictly a bug, but vanilla ToEE handles this by stretching the scene to fit (distorting the aspect ratio as necessary). Depends on how you look at it I guess (you could say the vanilla behavior was the bug :P)

As for scrolling, yeah I guess cursor at black zone -> scrolling will be ok.

**Comment by shartte** [comment]
There is also another way: Locking the cursor not to the window, but rather
to the scene rectangle in fullscreen mode. That way you kinda get the
vanilla behaviour back. The mouse just wont move into the black areas.

**Comment by DudeMcDude** [comment]
Sounds good too. Just need to make sure it doesn't interfere when alt+tabbing.

**Comment by shartte** [comment]
It shouldn't, we already lock the cursor to the window in fullscreen.
Windows automatically removes the lock when our window loses focus.
