### ISSUE TITLE
Fix Shutdown Crash in Main Menu

### ISSUE THREAD

**Issue by shartte** [GrognardsFromHell/TemplePlus#18]
The shutdown crash in main menu is caused by the Co8 world map extensions. Some list of widgets is extended and more widgets are freed, but it never seems to be initialized right. I cannot see the co8 code in IDA, so this is an issue.

**Comment by Shais2304** [comment]
Should be documented in the SpellSlinger files.

https://github.com/CircleOf8/DllDocumentation/blob/master/Spellslinger's%20Notes/worldmap_enhancement.txt

**Comment by DudeMcDude** [comment]
Ok, I think I fixed what Spellslinger did wrong - he changed the struct WorldmapWidgets (pointed to at 10BEF2D0), and expanded the "acquiredLocations" field (offset 0x200 through 0x234 expanded to 0x200 thru 0x250). There is another widget at the end of the struct though, originally at 0x238 (moved to 0x254) - he forgot to change this offset when freeing the widgets, which resulted in trying to free 0x238 twice, yielding a crash.

However, I still get a crash after fixing this - this time by d3d stuff :) your territory!
I don't think it's related, since I'm now getting this crash on GoG too.

**Comment by DudeMcDude** [comment]
Fixed in one of the latest updates
