### ISSUE TITLE
Vanilla / GoG: Problem with camera start location

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#184]
When running T+ with Vanilla / GoG, the tutorial map starts with the camera such that the character is at the top left.

May or may not be related, but the popup text doesn't show up there either (the one that's displayed when starting the tutorial).

**Comment by shartte** [comment]
How does that happen? :|

Are you sure there is no Python error or similar?

**Comment by DudeMcDude** [comment]
There's no python that directly scrolls the screen or controls the camera...

**Comment by Felipefpl** [comment]
I'm also having problems with the character in the upper left side outside of the screen but i'm not using Co8 or GOG's game, is it really mandatory? I have no use for Co8 since even the standard version introduces A LOT of new things in the game (i read the changelog). In case it is mandatory i wont report the other problems i found, i'm on win7 x64 with intel hd 2000 and 727 version.

**Comment by DudeMcDude** [comment]
Hi Felipe,

Co8 or GoG are not mandatory, and we definitely want to support the Patch 2 version. We'll fix this issue, and if you have other issues to report, please do so.

**Comment by DudeMcDude** [comment]
Update: apparently this only happens when running the game for the first time.

**Comment by Felipefpl** [comment]
"Hi Felipe,

Co8 or GoG are not mandatory, and we definitely want to support the Patch 2 version. We'll fix this issue, and if you have other issues to report, please do so. We'd greatly appreciate more testing done on Patch 2."

That's nice to know, thanks.
