### ISSUE TITLE
Port the rendering to DirectX 11 for better compatibility

### ISSUE THREAD

**Issue by shartte** [GrognardsFromHell/TemplePlus#208]
DirectX 9 is already a legacy API and our development tools only barely support DX9 debugging. We should port all rendering to DX11 to have better compatibility.

**Comment by Heinous-Hat** [comment]
I think that will break driver level anti-aliasing. Supersampling does a much better job at cleaning up character models than the native multisampling, imo. Would it be possible to implement a native solution of similar quality under dx11?

**Comment by shartte** [comment]
> I think that will break driver level anti-aliasing.
How so?

**Comment by Heinous-Hat** [comment]
I should say _might_ break..._ based on it not working for any current dx11 titles. I don't know the technical aspect, beyond setting the bit flags in the game profile having no effect.

**Comment by shartte** [comment]
We might be able to implement some other AA solutions in DX11, but the primary goal of porting to DX11 would really be compatibility. We have major issues with debugging the graphics core since the DirectX 9 debug runtime is no longer available since Windows 8 (!).
Our IDE only supports debugging DX11 graphics natively and even the NVidia tools we use are only still working for DX9 by chance (and barely, at that).

**Comment by Heinous-Hat** [comment]
Oh, I understand completely your reason for doing so... no argument :) You just piqued my interest since the profile override is a reliable means to improving image quality with older games. Been meaning to start a thread over in the forum demonstrating the benefits for ToEE, especially since the quality increased as you brought Temple+ to dx9. It allows you to run at an upscaled resolution (e.g. 1280x800) with the environment and characters at a comfortable size while actually improving IQ compared to the native AA at higher resolutions. I'll post some comparison shots in the near future.

As for the particulars of why that practice generally fails with dx11... it may be that the use of rendering methods common to that API are largely responsible, rather than simply utilizing that rendering path (by itself). Using AA overrides via profiles can also break under dx9, for example, when an application makes use of deferred rendering techniques. For whatever reason, Nvidia stalled in their effort to make forced AA work as a general solution under dx11 and have remained tight lipped as to why. Not sure how that goes with AMD hardware.

So hopefully it continues to function, or you can find a native solution...which would be better for everyone anyway (rather than fiddling with profiles and 3rd party utilities). I'll be interested in testing and providing feedback and suggestions, whatever the case.
