### ISSUE TITLE
TFE-X Replacement

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#21]

**Comment by shartte** [comment]
What tasks and features does TFE-X have? The only one I distinctly remember is being able to enable/disable the Co8 modpack itself.

We have a really neat, new feature we can use for that though: tig_path_add.
We can just prepend an arbitrary new data directory anywhere on the disk, hehehe. :)

**Comment by Shais2304** [comment]
* Zips/unzips modules and save games
* Manages applied DLL hacks like number of party members, number of Point Buy points, etc.
* Utilities such as "disable/enable intro" (renames the files IIRC)

Re. tig_path_add, are you suggesting to replace it entirely?

**Comment by shartte** [comment]
Regarding replacing: I don't know.

Zips/Unzips modules: Is there more than one currently? We could be able to skip this step entirely using the tig_path_add function. One possible way is to keep TFE-X and just make it write to TemplePlus.ini which additional module should be loaded. That'd possibly even skip the unzip step.

Is zipping save games meant to be a space-saver or backup functionality?

Managing DLL hacks / Utilities -> The actual functionality should be in TemplePlus.ini, TFE-X should manage the .ini file instead.

We could also actually make the ingame options dialog control a few of these :D

**Comment by Shais2304** [comment]
Modules: I'm talking about TFE-X modules (.tfm and .tam files) - these are basically zipped files containing the modified toee\modules and toee\data files. TFE-X manages the files in those folders when you switch TFE-X modules - deleting irrelevant files, backing up necessary files (saves, character files, etc), and deploying the new ones. This is the primary functionality of TFE-X.

I think the bare minimum of integration with TFE-X is that it should recognize when TemplePlus.exe is present and run that instead of toee.exe. I'll put the TemplePlus.ini integration as a bonus, particularly since it can cause some headaches with backwards compatibility.

We've had some relevant discussion with Agetian in the past about the short-lived TempleExtender project, if you recall. I'll quote:


> I'm looking through the TFE-X code right now and I think that while the change seems simple enough (change temple.dll into temple.org.dll everywhere) it might actually be a pain in the butt to implement it properly. The TFE-X implementation depends on the following:

When and how does the duo-DLL implementation come in? If it's a part of the module, TFE-X (without a rather serious rewrite) will not be able to differentiate between the old-style (with only one temple.dll) and new-style (with two temple.dlls, one of which is temple.org.dll) implementations and this will break the compatibility with all previous versions of the Co8 Mod and KotB modules and add-ons. Moreover, if left just like that, TFE-X is likely to just break any installation with mixed old-style and new-style modules upon the first attempt to install an old-style module. However, if the duo-DLL configuration is not a part of the module package and is installed separately, it complicates the matter even more since TFE-X will need to be taught to detect it when it's there and forget about it if it's not there and resort to the old mechanism.

What I will try to do is I will try to only make the said change affect the patches (Spellslinger's and Drifter's mods and whatnot), teach it to inject the patches into temple.org.dll if it's present and to temple.dll otherwise, but once again, I think it's going to break compatibility with the previous versions of the mods simply because after a new-style configuration is deployed (temple.org.dll etc), it will not be auto-removed by TFE-X upon the deployment of an old-style module on top of it, which also equals undefined behavior (likely the break of the old patches on the old modules). This part would also ideally need a rewrite.

Now, the biggest problem of it all: my life is crazy at the moment and I'm not sure if I can tackle a 50% rewrite of TFE-X at the moment, let alone tackle it carefully and properly. If anyone wants to volunteer, I'd gladly donate the source code to the latest version of TFE-X, provided that all the original credit lines will be left intact (and of course that person will insert himself into the credit line as well as a project contributor).

I'm waiting for your input, guys. If there's a volunteer to tackle this, please send me your e-mail as well. 

- Agetian

Quote:
Originally Posted by DarkStorm
Well, it depends, really.

There are multiple ways of "fixing" this issue.

Is the source code for the ToEE frontend available somewhere?

There's also another thing I can do in my proxy-dll actually. I can redirect file-system access to certain directories (I did the same thing years ago for Ultima Online). If i remember correctly, right now the Frontend copies files around to get multiple modules to work, right? This could be modified so the proxy DLL redirects file access to the selected module directory without actually having to copy anything around.

Regards,
Storm
