### ISSUE TITLE
Latest version making my computer too hot

### ISSUE THREAD

**Issue by pelador** [GrognardsFromHell/TemplePlus#220]
Performance related issue. Ever since installing the latest update, the game seems to be pushing my computer much harder than it did before. After I closed the game, my CPU was over 66 degrees Celsius with the side panel off. Of course I could just play in windowed mode, but I shouldn't have to. I think that if I can play The Witcher III with no issues then this old game should be a piece of cake too, but it isn't right now. Any advice is appreciated.

**Comment by DudeMcDude** [comment]
What are your system specs?
Are you running anything in the background?
Have you turned on Soft Shadows?

If this persists, please post a logfile and a savegame demonstrating this. Otherwise I'm seeing a ~10% CPU load when running the game, and the latest update is just a couple of fixes that should have no relation to it.

**Comment by pelador** [comment]
I'm using Windows 10 with a third generation i7 3770k 3.5ghz with an AMD Radeon R9 390 GPU. 

Actually turns out the problem was related to me running it from the start menu. Running TemplePlussetup.exe from it's original location instead doesn't give me any problems.

**Comment by DudeMcDude** [comment]
I highly doubt it's related... At any rate it sounds like a fluke, but let me know if it happens again.

**Comment by shartte** [comment]
There are some cases when ToEE just for some unknown reason consumes a LOT of cpu cycles when idling on a map. It goes away after changing maps though.
