### ISSUE TITLE
Anim freeze issue

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#326]
To recreate:
Create new character
Start the game with that character

**Comment by shartte** [comment]
It's unclear what set the flag to 1 in the first place, but "pushGoal" thought the anim system was still loading from a save-game, although the loadFromSave function was never called to begin with (due to using New Game). I now reset the flag in reset() for the anim system as well as in the constructor which fixes this issue for me.
