### ISSUE TITLE
New classes spell issues

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#341]
See report here:

https://rpgcodex.net/forums/index.php?threads/temple-support.98897/page-2#post-6179547

**Comment by doug1234** [comment]
Looks pretty fixable.  I plan to do some modding later this week and should be able to get it done then.

**Comment by doug1234** [comment]
I think the only mistake on the spell list was having mass hold monster at 9th level.  I am looking into the wrong spell list being displayed.

BTW:  I agree with you that hold spells are mind effecting and not paralysis effects.

**Comment by DudeMcDude** [comment]
Yeah that was my understanding, but I found another rules lawyer thread that said otherwise. I've already changed it, going to push the fix when i get the chance.

**Comment by doug1234** [comment]
Interesting.  If you are going to change it you will probably have to make changes to effects like freedom of movement if you want the game to handle it consistently.

**Comment by DudeMcDude** [comment]
How so?

**Comment by doug1234** [comment]
Freedom of movement provides paralysis immunity so to be consistent I think it needs to provide immunity to the hold spells.  I don't think it currently does (but I am not 100% sure).  I can check on that tonight.

**Comment by doug1234** [comment]
Looks like freedom of movement is indeed working correctly with hold person.

**Comment by doug1234** [comment]
Disabled advanced learning for prestige classes.

**Comment by Feanar-Ringfaroth** [comment]
Hello, I don’t know if I have to reply in this Issue, let me know and I will create a new issue. 

I have a Favored Soul Lv 19th (Aasimar). When I try to level up to Lv 20th of FvS I cant choose a 4th spell of 9th level. This is because is only three 9th level spells in the divine spell list for clerics. So, I can finish to level up. I need necessarily a 4th spell in the list of 9th level spells. For now I will opt to level in other class because I love this game! But I will be much appreciate if this bugs resolves. 

If I may… I think “Visage of the Deity, Greater” is a good choice to add to the list of 9th level spells (Is from Complete Divine complement)…. I know that I’m asking too much because I don’t know how to develop new spells… but the bonuses to abilities, DR and other stuff is doable… or not?

P.D.: Sorry for my English,.. I hope you could understand my explanation of the problem… Thank you!!

**Comment by doug1234** [comment]
I think that should be fixable.  I had to fix something similar for warmage and beguiler advanced learning.  I'll see if I can fix it next week.

**Comment by Feanar-Ringfaroth** [comment]
Thank You!!! You are great!!
