### ISSUE TITLE
cant compile 

### ISSUE THREAD

**Issue by Red-Kai** [GrognardsFromHell/TemplePlus#375]
hi , last build was in June last year .
trying to compile from the latest code , I'm getting 

Error C1047 The object or library file 'D:\Games\Temple of elemental evil\TemplePlus-master\Release\\temple.lib' was created with an older compiler than other objects; rebuild old objects and libraries	ParticleEditorNative	D:\Games\Temple of elemental evil\TemplePlus-master\Tools\ParticleEditorNative\LINK	1

**Comment by shartte** [comment]
TemplePlus still has not updated to VS 2019, you'll need to use VS 2017.
If you want, you can use the VS 2017 compilers with the VS 2019 IDE by having both installed, as far as I know.

**Comment by Red-Kai** [comment]
This error is on VS 2017- same one I used to be able to compile with . were there any changes to the SDK version ? maybe you could just publish updated build ?

**Comment by doug1234** [comment]
Sounds like you might be in need of a rebuild.  Have you done a full rebuild yet?

**Comment by Red-Kai** [comment]
Yep Tried to rebuild . same issue . any chance you can post an updated Release ?

**Comment by shartte** [comment]
@Red-Kai: Can you please go into "D:\Games\Temple of elemental evil\TemplePlus-master\Release" and delete the temple.lib there? I was actually mistaken about my comment, because i thought it was the precompiled dependency-package that created this issue for you, but temple.lib is created as part of the normal compilation process.
The only reason I can think of is upgrading Visual Studio 2017 at some point, and it not cleaning up previously compiled libraries.

**Comment by Red-Kai** [comment]
@shartte - same error - I deleted temple.lib , clean the project and then rebuilt.

Error	C1047	The object or library file 'D:\Games\Temple of elemental evil\TemplePlus-master\Release\\temple.lib' was created with an older compiler than other objects; rebuild old objects and libraries

**Comment by shartte** [comment]
@Red-Kai Hmmm weird. Can you report which version of Visual Studio 2017 you are running? I am going to try a clean build with the same version on my machine.

**Comment by Red-Kai** [comment]
@shartte - vs2017  - 15.9.20 .
I really appreciate your help!

**Comment by shartte** [comment]
No probs. I'll have to update first, though.

I also created a task to update to VS 2019 (#378).

**Comment by shartte** [comment]
Okay, I can confirm, after Updating VS 2017, I do get a similar (albeit not the same) issue:

13>LINK : fatal error C1047: The object or library file 'C:\TemplePlus\TemplePlus\dependencies\lib\python27.lib' was created with an older compiler than other objects; rebuild old objects and libraries

I'll wait for feedback on updating to VS 2019 and likely to that instead of bothering with updating the dependencies for the latest VS 2017 compiler.

**Comment by Red-Kai** [comment]
@shartte - thank you for confirming . any change you can post a new release exe  in the meantime ?

**Comment by shartte** [comment]
If you just want a recent executable, you can always download the latest one from AppVeyor:

https://ci.appveyor.com/project/templeplus/templeplus

(Click on the "Artifacts" tab)

**Comment by Red-Kai** [comment]
Thank you , I did not know about this one .

**Comment by shartte** [comment]
@Red-Kai Do you still want to try compiling? We have upgraded to VS2019 by now. If not, can we close this issue?

**Comment by Red-Kai** [comment]
@shartte - I'm able to compile it fine now with VS 2019- thank you for the super quick reply - and for the amazing work here .
