### ISSUE TITLE
Flasks of oil/acid disappear when equipping during battle

### ISSUE THREAD

**Issue by uralets** [GrognardsFromHell/TemplePlus#461]
Latest Co8, T+

A reference to this issue https://co8.org/community/threads/bottle-throwing-items.10492/#post-135948

Dragging/r-clicking a throwable flask into a hand slot during a battle makes the flask disappear.
Whatever the char was holding gets placed properly in the inventory. But the slot is just empty.
The flask is nowhere to be seen (not dropped, doesn't end up in another weapon combo).
Freeing the hand manually before trying to equip the flask doesn't help.

This doesn't happen with Holy Water though.

**Comment by DudeMcDude** [comment]
This is related to your other issue with the corrupt save. As it turns out, they're both caused by a script that is meant to delete the thrown flask when it hits a critter.
A related vanilla ToEE bug: the "grenade" thrown item doesn't explode, and reappears on the corpse as though it were a throwing dagger/javelin etc. Looks like the root cause is the game doesn't recognize it's a grenade throw action from the auto-attack action, whereas throwing it by using the manual radial menu option works correctly.

**Comment by DudeMcDude** [comment]
Both issues should now be fixed.
