### ISSUE TITLE
Passed/resting time is incorrectly related to rounds time

### ISSUE THREAD

**Issue by dolio** [GrognardsFromHell/TemplePlus#497]
Here's another fun vanilla bug.

Passing time/resting does not tick the correct number of rounds. I think the current behavior is 1 round ticked for every hour of time passed. This means that if you set an hours-long spell's duration to the correct number of rounds, it can last for weeks/months of rested time.

The reason for this behavior is that the `Camp()` function runs a loop that counts off the hours and does an appropriate `AddTime()` (and checks for other stuff). `AddTime()` calculates the number of rounds passed and calls `D20ObjRegistryBeginRoundForAll()` with that number. That function calls `Dispatch48BeginRound()` with the number of rounds. Then that last function ignores the calculated number of rounds. So you get 1 round per hour.

**Comment by DudeMcDude** [comment]
That's not a vanilla bug actually, Temple+ original - oops! I even commented out numRounds and put 1 in there. This was 5 years ago actually, but I only used that functions for the combat begin round rather than for total replacement. 
Recently I've replaced the function itself so the bug became visible. Only in the dev build thankfully :)
