### ISSUE TITLE
d20_ai_utils.py - Accessing unsupported field obj_f_npc_ai_flags64

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#661]
if critter is PC then this should not happen:
ai_flags = critter.obj_get_int64(obj_f_npc_ai_flags64)

**Comment by DudeMcDude** [comment]
Thanks, I think this was due to a bug in will_kos, it had a flipped condition:

`if target.type == obj_t_npc:`

instead of

`if target.type != obj_t_npc:`

In general it shouldn't be trying to even get AiFightingStatus for PCs. I guess in some rare cases it could happen, e.g. if you use the import party feature from DM or somehow spawn PCs.

I'll push a fix for that line, which I think should do it, but let me know if you run into this again.
