### ISSUE TITLE
SpellSoundPlay EndSpellCast crash 

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#697]
![image](https://user-images.githubusercontent.com/40269424/187512588-edec9d3b-cfbe-4388-9eea-5f7d6702598f.png)
My PC had Bane on him, so when I wen to next map and tried to rest crash went off.

See last log message in the pic.

**Comment by DudeMcDude** [comment]
I think I fixed this issue recently. 

It was due to the Jammed Spell garbage collection, which had an issue with invalid caster handle when the caster wasn't in the party. It called SpellEnd, triggers the EndSpellCast event and tries to play the end spell sound on the caster, which is no longer valid.

Can you confirm it's closed?

Also, just to verify, you were running a dev build, right?

**Comment by anatoliy-savchak** [comment]
Thanks!

Cannot confirm as I lost the save. But looked at the code fix, should be covered.
