### ISSUE TITLE
Particle Lag bug

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#94]
Hypothesis:
http://www.co8.org/forum/showpost.php?p=100917&postcount=30

**Comment by shartte** [comment]
Pinging @DudeMcDude 
Is this resolved by my sector cache fix?

**Comment by DudeMcDude** [comment]
No
In GF's computer, just had a lock up of a few minutes (!!!) in the fire node. In other words, same old.

This was after I left the computer running for about half an hour in the fire node, and then scrolled over. Classic node lag.

Was using GoG version since Co8 removed particle effects from critters, which (according to the above hypothesis) bypasses the problem.

**Comment by DudeMcDude** [comment]
Ah, on second thought, the above may have been a device loss issue.

**Comment by shartte** [comment]
that may actually then be the simulation issue. i  thought i ironed that out, but i think i reverted the fix because the thing we actually looked at ended up being related to sector caching.

**Comment by DudeMcDude** [comment]
Here. Use the GOG version.

https://drive.google.com/open?id=0BzF5KfpDewVYS29WMTczNUhHbFk

Load the save, wait a few minutes, and the scroll to top right direction. Should get a nice hang (more than a minute in my case).

**Comment by shartte** [comment]
Bug fixed. This should cause a general performance improvement where non-permanent particle systems on objects were involved.

**Comment by shartte** [comment]
Just an explanation for posterity (gave one in the commit message as well):

ToEE tracks lifetime for particle systems and their emitters separately.
While a particle system is off-screen, the lifetime of the system is increased, but not of it's emitters, because it needs to actually run the particle simulation to reliably increase that lifespan value.
The bug is this: ToEE checks the *emitters* lifetime's, not the particle systems when it tries to determine whether a particle system has expired.

Coupled with the fact that the animation system will keep spawning particle systems even for models that are offscreen, a huge number of particle systems will accumulate over time. Most of them actually dead. But as soon as you scroll them into view, ToEE will faithfully simulate all the emitters that now still have a lifetime of 0 until they expire. This causes a multi-second simulation loop.

The fix is simple, really: I now calculate the max. lifetime of the overall system and compare the system's lifetime against that value *even if it's off screen*. If the result of that check is that it has expired, i destroy the system immediately. 

Effect: Instead of thousands of systems after a few minutes, the number of active particle systems in the fire node doesn't exceed 50.
